Traceback (most recent call last):
  File "/home/user/PycharmProjects/python_advanced/module_05_processes_and_threads/homework/hw4/test_redirect.py", line 10, in test_stdout_stderr_was_indeed
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
